name: Set up profile cards

on:
  schedule:
    - cron: "15 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: svg-store

      # Night versions of the cards
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=codeSTACKr\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: utils/stats-night.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: "username=${{ github.repository_owner }}\
            &layout=donut\
            &langs_count=6\
            &theme=great-gatsby\
            &show_icons=true\
            &count_private=true\
            &hide_border=true"
          path: utils/languages-night.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      # Day versions of the cards
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=moltack\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: utils/stats-day.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: "username=${{ github.repository_owner }}\
            &layout=donut\
            &langs_count=6\
            &theme=rose\
            &show_icons=true\
            &count_private=true\
            &hide_border=true"
          path: utils/languages-day.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[kev-bot]"
          git config user.email "github-actions[kev-bot]@users.noreply.github.com"
          git add utils/*.svg
          git commit -m "bot(readme): refresh profile stats cards" || exit 0
          git push origin svg-store --force
