name: Set up profile cards

on:
  schedule:
    - cron: "15 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: svg-store

      # Night versions of the cards
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=gruvbox\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-gruvbox.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=tokyonight\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-tokyonight.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=algolia\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-algolia.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=vue-dark\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-vue-dark.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=gruvbox\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-gruvbox.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=date_night\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-date_night.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=holi\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-holi.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=codeSTACKr\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-codeSTACKr.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=aura_dark\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-aura_dark.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=ocean_dark\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-ocean_dark.svg
          token: ${{ secrets.GH_PROFILE_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}\
            &show_icons=true\
            &theme=vision-friendly-dark\
            &count_private=true\
            &include_all_commits=true\
            &custom_title=Kev%27s%20GitHub%20Stats\
            &show=reviews,prs_merged\
            &hide_border=true"
          path: tests_themes/stats-vision-friendly-dark.svg
          token: ${{ secrets.GH_PROFILE_PAT }}
